### ISSUE TITLE
Missing support for literal operators

### ISSUE THREAD

**Issue by trikko** [atilaneves/dpp#101]
For example:

```c++
string::operator""s
```
like in:

```c++
std::string s2 = "abc\0\0def"s;
```

**Comment by trikko** [comment]
Just a note: this prevent some headers from be compiled. It sounds more like a bug than a enhancement.

**Comment by atilaneves** [comment]
I've changed the label accordingly.

**Comment by atilaneves** [comment]
Out of curiosity, which headers use this? `using namespace` shouldn't be used in headers, so I'm struggling to understand which headers would have the literal operators available without qualification.

**Comment by trikko** [comment]
Uhm good point. I didn't realized it. 
Indeed the problem in headers seems to be this one:

https://github.com/gcc-mirror/gcc/blob/7652827de451fc243cc16f3b4c1f36fda761f91e/libstdc%2B%2B-v3/include/bits/basic_string.h#L6727

that is the declaration itself.

Here a simple test file:

```c++
int operator""s(const wchar_t* __str, unsigned long __len);
```
I'm sorry for the misunderstanding.
