### ISSUE TITLE
Translate non-function-like macros into enums

### ISSUE THREAD

**Issue by atilaneves** [atilaneves/dpp#103]
That way the constants can always be imported without explicitly appearing in the #including dpp file.

**Comment by atilaneves** [comment]
Compromise: macro constants become `DPP_ENUM_` prefixed to the original macro name. The original macro is also still available for use in the dpp file that #includes the header.

**Comment by trikko** [comment]
why not:
#define MY_MACRO 33
->
Macro.MY_MACRO 
instead of
DPP_ENUM_MY_MACRO?

**Comment by atilaneves** [comment]
@trikko Because that's a lot more work ;) :P

I'd have to record all constant macros and create a namespace for them such as a template to insert them all at the end. I like the idea though. Probably better to be `dpp.macro.MY_MACRO`. Feel free to open an enhancement issue.
