### ISSUE TITLE
Change C-compiler

### ISSUE THREAD

**Issue by sr-tream** [atilaneves/dpp#105]
Hello, I build library for windows, from linux. I use ldc2 for cross-compile, but D++ using GCC an I can not change it to i686-w64-mingw-gcc.
Please add flag to change C compiler.

**Comment by atilaneves** [comment]
I'm not sure what you're asking for. dpp doesn't use a C compiler at any point.

**Comment by sr-tream** [comment]
Understood. It seemed to me that errors related to __declspec output C compiler
