### ISSUE TITLE
Template partial specialization

### ISSUE THREAD

**Issue by trikko** [atilaneves/dpp#108]
```c++
template<class T1, class T2, int I>
class A {};            

template <typename CC> class C {};

template<class T, int I>
class A<C<int>, T*, I> {}; 
```

**Comment by atilaneves** [comment]
This originally failed due to a silly algorithm for translating types, but after that was fixed, the real issue is translating:

```c++
template <typename T>
class A<int, T*, 42>
```

to the correct D declaration. My brain is a bit fried right now, but even writing the declaration manually I'm not sure if it's possible.

**Comment by atilaneves** [comment]
How is the C++ code supposed to be used? This doesn't compile:

```c++
#include <iostream>

using namespace std;


template<class T1, class T2, int I>
class A {
public:
    enum { value = 0 };
};

template <typename CC> class C {};

template<class T, int I>
class A<C<int>, T*, I> {
public:
    enum { value = 3 };
};


int main() {
    cout << A<int, 42>::value << endl;
}
```

**Comment by trikko** [comment]
It was a reduced version of real code from one of the libraries I plan to use. Maybe I was wrong with reduction...

**Comment by atilaneves** [comment]
@trikko Right now I can't do anything about this, since I don't know how to manually translate this code. There was a different issue with it though that was fixed, so I'll close it.
