### ISSUE TITLE
Allow replacing and making opaque types

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#111]
Until dpp can handle everything, it's presently at the mercy of one line in one file at the bottom of the include graph that it can't handle.

Common sense and it turns out what people in other technical communities have done with some success suggests why not just replace a type you can't yet translate with either a manually crafted replacement, or worst case a blob of bytes.  You might not even have public access to the members of that type so from D perspective you couldn't care less whether it's a blob or properly done.

So if you declare types on the opaque blacklist by regex then it just replaces them with ubytes.  How many ?  Many enough so the next member is in the right location or offset of, I think using this function.

There must however be some edge cases where this causes problems.  For ages in D extern (C) if you had a small struct with a floating point member in it then it was passed using the wrong calling convention.  I think an optimisation to pass in registers went wrong somehow.  So it must matter in some cases if you misdeclare what's in it.  However Rust guys don't seem to have problems and maybe this is only relevant for small structs.

GC is another factor.  I guess just don't let GC pointers end up in a blob,but that's easy enough to avoid.

Anyway I think if I understood right code changes are just to translateAggregate mostly and use function below to get alignment right if it's a type that is opaque?

If you then just skip CPP stuff you can't handle,I think maybe a lot more is not far off being usable.

long clang_Cursor_getOffsetOfField(in CXCursor C) @safe @nogc pure nothrow;

---
code wins arguments ;)
see PR #112

**Comment by atilaneves** [comment]
This has been implemented now.
