### ISSUE TITLE
reopening namespaces

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#113]
when namespaces are reopened then have problems with forward declaration.  I think need to gather all declarations in each namespace and open an extern(C++) extern(C++,"foo") extern(C++,"bar") for everything in foo.bar namespace rather than reopening as currently happens.

**Comment by atilaneves** [comment]
Could you provide an example please? D doesn't need forward declarations at module scope, so I can't see how this would come about.

**Comment by Laeeth** [comment]
Try autowrapping any non trivial C++ project using my fork.  (yours won't finish because it will choke on things I just turn into an opaque).  You will see what I mean.  I will create test case if /when time.

**Comment by Laeeth** [comment]
The problem is that D forbids forward declarations!

It comes about via recursive header imports.

Example - try include bond convention.h

**Comment by atilaneves** [comment]
I googled `bond convention.h` but didn't find anything. Is is this open source?

**Comment by Laeeth** [comment]
I sent you a link before.
Git.kaleidic.io
Xenoncpp

**Comment by atilaneves** [comment]
> The problem is that D forbids forward declarations!

D forbids more than one declaration. Forward declarations are fine as long as they're the only one.

**Comment by atilaneves** [comment]
Command to try it:

```
./d++ --include-path ~/kaleidic/xenoncpp/Analytics/Analytics.Rates --include-path ~/kaleidic/xenoncpp/Analytics/Analytics.Numerical --include-path ~/kaleidic/xenoncpp/Analytics/Dlang/cpp --include-path ~/kaleidic/mir-algorithm/include --parse-as-cpp --ignore-macros xenon.dpp
```

**Comment by atilaneves** [comment]
For now I'm hitting a lot of unstranslatable cursors from boost but not anything to do with namespaces.
