### ISSUE TITLE
enum inside a struct should be referred to by its full name outside the struct

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#119]

**Comment by atilaneves** [comment]
It already is:

```c
                struct Struct {
                    enum Enum { foo, bar, baz };
                };
```

Currently translates to:

```d
struct Struct
    {
        static enum Enum
        {
            foo = 0,
            bar = 1,
            baz = 2,
        }
        enum foo = Enum.foo;
        enum bar = Enum.bar;
        enum baz = Enum.baz;
    }
```

**Comment by Laeeth** [comment]
No the translation of code outside the struct.

eg boolCheckType(Struct s, Struct.Enum e)

Some cpp code gets rendered as just Enum e

**Comment by atilaneves** [comment]
That's fine: the idea is to emulate the behaviour one would get from C or C++. There, enums (but not class enums in C++ post 11) pollute the global namespace.

**Comment by Laeeth** [comment]
Yes, but right now dpp breaks class enums and I wish that it would not.

**Comment by atilaneves** [comment]
> Yes, but right now dpp breaks class enums and I wish that it would not.

Ah. That's a different story. I also realise I didn't understand correctly your example with `boolCheckType` above.
