### ISSUE TITLE
Blob override mapping

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#129]
Allow user to specify mappings in a table 
Eg
std.vector, core.stdcpp.vector
boost.variant,kaleidic.cpp.boost.variant,withsize

With size option means dpp should precede template arguments to replacement type with the size of blob required.  Reason for this is in general a D type can't know for sure how much space cpp type takes up unless it reimplements whole logic.

**Comment by Laeeth** [comment]
Yes indeed re former.

I don't at all see how your suggestion works.

core.stdcpp.vector is already implemented for Windows in druntime - see Manu requests.

And fact is if somebody specifies std:: vector in their project your suggestion doesn't seem to be likely to help.  More than that even with boost types that have the same name as std types...

I think that the idea of being able to wrap header files, one D file for each doesn't really work for a considerable number of commercial projects because of recursiveness and the way that preprocessor works.  So I suspect you may well be better off including everything at once, and then sorting out the mess.

For C++ projects simple enough -gather together namespaces split between headers and make the D module files by default reflect the namespace structure.  I think I have almost done this if you look at latest commit.

Same thing with system headers.  I think you end up with a mess if you make each D file represent one header or small group of headers.  You will have std:: vector defined from scratch everywhere!

Clang allows you to distinguish between system headers and user headers.  It's probably a good idea to have an option to write user headers only (and then do system ones separately) though I have sort of done this with the namespace idea.

This is still sort of compatible with the original idea of keeping the preprocessor but will explain later.

Anyway I have already implemented the mappings.  They work for simple things but a few things to iron out.

It's not just for system types but also user types.  Eg where you have C++ structures wrapping D structures.  I would quite like to just replace the C++ ones by D ones there where possible.

Try including Xenon and then tell me if you still don't see why!  You have access.

After my changes quite a few of the headers I tried were close to just working with only trivial things I know how to fix not working.  I'm sure there will be other problems.

But blacklisting headers and listing types as opaque or remapped helped a lot.  As did temporarily unavailable undoing operator templating (I couldn't figure out how to get the number of template arguments) and especially fixing forward declarations.

There's just so much junk from recursive includes that some kind of restriction is the only way towards sanity!

**Comment by Laeeth** [comment]
So eg above you would blacklist system headers for user code.  And handle them separately in a different dpp file.

Find me a widely used C++ header translation tool for a grown up language that isn't highly dynamic that doesn't allow quite fine configuration.  Even Clif from Google (where python dynamic nature should allow you to represent almost anything) is very configurable.  Same thing with cppsharp.

And effectiveness is demonstrated already - took minutes to add boost variant and the whole set of initial changes took me maybe half a day.  Whereas before I wasn't able to get very far with C++ and dpp.  I know that it's also because timing is right and you added some key features.

**Comment by atilaneves** [comment]
I'll try including xenon and see how far it gets me.

I still don't understand the need for mappings - it's an `alias` away or the user just needs to import things differently. Say that `core.stdcpp.vector` already exists:

```d
template stdcpp {
    static import core.stdcpp;
    alias vector = core.stdcpp.vector;
}
```

**Comment by Laeeth** [comment]
Ah so you use template for namespace

**Comment by atilaneves** [comment]
Yes - or D packages, modules, etc. D already has good ways to disambiguate names or to rename them entirely.
