### ISSUE TITLE
allow specification of arbitrary clang command-line arguments

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#144]
here:
```d
private from!"clang".TranslationUnit parseTU

    auto parseArgs =
        includePaths.map!(a => "-I" ~ a).array ~
        context.options.defines.map!(a => "-D" ~ a).array
        ;
```

**Comment by atilaneves** [comment]
After considering this for a while, I think a generic `--clang-option` should work similarly to the way dmd uses `-L` to pass options to the linker.

**Comment by Laeeth** [comment]
Conventionally also - - to indicate following arguments are passed to the application
