### ISSUE TITLE
Test for passing a struct or class with non trivial copy con or destructor

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#151]
Which has a different abi at least on linux 64
https://forum.dlang.org/post/m6qnfg$1hhh$1@digitalmars.com

https://github.com/rust-lang/rust-bindgen/issues/778

```

#include <cstdint>

struct Foo {
    size_t data;
};

struct Bar {
    size_t data;
    ~Bar() { data = 0; }
};

Foo MakeFoo(); // { return Foo(); }

Bar MakeBar(); // { return Bar(); }


If a C++ object has either a non-trivial copy constructor or a non-trivial
destructor 11, it is passed by invisible reference (the object is replaced in the
parameter list by a pointer that has class POINTER) 12

This means that while Foo get returned by-value in the rax register, Bar must be returned by-pointer to a caller allocated memory. 
```

**Comment by atilaneves** [comment]
According to the forum post, the destructor didn't link, likely because the mangling was incorrect. Given that the example above and in the bindgen issue is with non-templated structs, mangling can't be wrong due to `pragma(mangle)`.

Anyway, the test for this passes.

**Comment by Laeeth** [comment]
See this too
https://issues.dlang.org/show_bug.cgi?id=19563
@atilaneves

**Comment by Laeeth** [comment]
And this
https://issues.dlang.org/show_bug.cgi?id=19179

Windows treats structs that aren't POD differently if they are less than 8 bytes. That's the root of the problem.

A solution would be to add an attribute "@NotPOD struct blah { }" or something, rather than having to put an empty constructor. Not exactly something that is easy to notify the user of if this inconsistency exists.

**Comment by atilaneves** [comment]
Those two are dmd bugs that should be fixed - one could argue for dpp trying to bypass it but I don't see the point since it's better fixed at the source.

**Comment by Laeeth** [comment]
Dmd and maybe others.

Dpp doesn't need to fix it but should have a failing test for it.
