### ISSUE TITLE
dub support

### ISSUE THREAD

**Issue by John-Colvin** [atilaneves/dpp#25]
I started adding `dub` support, see https://github.com/John-Colvin/dub/tree/dpp_support and read the stuff at the top of the README. All it does is just treat `.dpp` files the same as `.d` if `dppSupport true` is set in `dub.sdl`, but that should be enough to make it work.

Missing pieces in `dpp` to make it work (bringing it closer to a drop-in for the compilers it’s wrapping) are:

1) support for 0 and >1 `dpp` files. Per file: output placed in same location as input (so imports work). 0 is needed so dub can get build information
2) support for `.rsp` files like dmd.

**Comment by atilaneves** [comment]
The multiple .dpp files is something I was planning already. I hadn't thought about the import implications.

I have no idea what an .rsp file is.

**Comment by John-Colvin** [comment]
dmd supports `@<cmdfile>       read arguments from cmdfile`, for some reason `.rsp` is the extension everyone uses for this file.

See https://github.com/John-Colvin/dub/blob/f4592fdfebbcf6d439dcd66942129445b0327230/source/dub/compilers/dmd.d#L199 where `dub` puts all it's command line arguments in a `.rsp` file then calls `dmd @<that rsp file>.rsp`

The reason it exists is to avoid command-line length restrictions, probably Windows is the primary culprit here.

**Comment by John-Colvin** [comment]
w.r.t. output locations, the default assumption should be that either the user wants the `.d` files in the same places as their corresponding `.dpp` files, or optionally with the same directory structure with a different root so you could have a `.dpp` tree under `dppSource` and expect the output in `dSource`. The former is much more important though.

Seems like `output-file` only makes sense when you're passed one input file, having some plural `output-files` just seems like an interface nightmare.

**Comment by atilaneves** [comment]
The default assumption right now is that the user doesn't even want to see the .d file, so it gets deleted (but that can be prevented with `--keep-d-file`). But yes, unless `--d-file-name` is used, the .d file is named just as the .dpp is, including the path. There's currently no option to use the same directory structure with a different root.

To make it simple, `--d-file-name` (the old `--output-file`) should probably only be relevant if there's only one .dpp file.

**Comment by atilaneves** [comment]
I'm not sure what situation dpp was in when this was opened. From the dialogue, it still didn't handle multiple .dpp files at once. It does now.

The other thing was .rsp support, but given that dpp forwards all its arguments that aren't its own command-line options to the compile anyway, it's transparent. i.e. `d++ @whatever.rsp` works right now.

Given the points above, I'll close this.
