### ISSUE TITLE
Build on Debian Sid requires edit of dub.sdl file

### ISSUE THREAD

**Issue by russel** [atilaneves/dpp#256]
In order to build DPP on Debian Sid, I had to edit the dub.sdl file. I replaced the Travis-CI lflags line with:
```
lflags "-L/usr/lib/llvm-9/lib" platform="posix"  # for Russel's Debian Sid
```

**Comment by atilaneves** [comment]
I don't know how else to deal with different libclang locations. I'd suggest changing environment variables or symlinking to /usr/lib.

**Comment by russel** [comment]
For me, and others, amending manually anything in /usr is a no-no since that is a package managed area. I was wondering though if there was a way Dub for DPP could handle an environment variable. Doing:
```
(export LD_LIBRARY_PATH=<path-to-llvm>; dub build --build=release)
```
seems not to work.

**Comment by atilaneves** [comment]
dub doesn't work well with environment variables. I still don't know why libclang would be in a non-standard place on other distributions - it makes no sense to not put it in `/usr/lib`. Another reason for me to like Arch the best, I guess.

**Comment by russel** [comment]
I think the Debian thinking is that all LLVM version can coexist at the same time, hence the version specific naming. The question is, I guess, why there is no alternatives system over the top to decide which is the current version. That is actually a bit strange.

Anyway, it seems I am stuck with manually hacking dub.sdl, which, whilst irritating, is fine if I know there is no other way.
