### ISSUE TITLE
you should not translate types which have no equivalent in D. such as float128 .... is that even a  thing in C ?

### ISSUE THREAD

**Issue by stefan-koch-sociomantic** [atilaneves/dpp#28]
https://github.com/atilaneves/dpp/blob/be7ecf326042ac8423f354470a6a37697480bfcb/tests/ut/type.d#L131

**Comment by atilaneves** [comment]
It's a thing in libclang, otherwise I'd never heard of it. I don't know if it's better to throw an exception or keep it the way it is.
