### ISSUE TITLE
C11 Anonymous structs and unions lead to wrong D code

### ISSUE THREAD

**Issue by cym13** [atilaneves/dpp#29]
**Given the following files**:

*test.h*

    typedef struct {
        union {
            struct {
                double x;
                double y;
                double z;
            };
            double raw[3];
        };
    } vec3d_t;

*test.dpp*

    #include "test.h"

    unittest {
        vec3d_t v;
        v.raw[1] = 3.0;
        assert(v.y == 3.0);
    }

**Running**:

    d++ -unittest test.dpp

**We expect**: no error.

**We get**: the following error:

    Error: Could not execute `dmd -unittest test.d -oftest`:
    test.d(27): Error: no property `raw` for type `vec3d_t`
    test.d(28): Error: no property `y` for type `vec3d_t`

**Workaround**:

Not sure. Reusing the anonymous name would only lead to messy code. Renaming
the internal struct seems best but requires postprocessing.

**Version**: commit be7ecf326042ac8423f354470a6a37697480bfcb

**Comment by atilaneves** [comment]
Good catch. I never would have thought of testing this.

**Comment by cym13** [comment]
I tested it as a simplified case of trying to use X11/Xlib.h but truth is I'm not even sure they're the exact same issue. Using d++ on a file containing only « #include <X11/Xlib.h> » results in a compilation error with the following message:

    Error: Could not execute `dmd test.d -oftest`:
    test.d(797): Error: { } expected following `struct` declaration
    test.d(797): Error: { } expected following `struct` declaration
    test.d(797): Error: declaration expected, not `(`
    test.d(2027): Error: unrecognized declaration

Which points to the following line 797:

    struct struct (anonymous at /usr/include/X11/Xlib.h:493:9)

which doesn't look valid but refers to anonymous strucs hence this issue.

If you do not think that they are the same issue I can open a new one.

**Comment by atilaneves** [comment]
I'll look into X11/Xlib.h - it's a good way to test dpp anyway.

**Comment by sarneaud** [comment]
Here's another real example: version 2.25 of glibc (but not 2.27 or a few others I checked) has this code in pthreadtypes.h:

```
/* Data structure for conditional variable handling.  The structure of
   the attribute type is not exposed on purpose.  */
typedef union
{ 
  struct
  { 
    __extension__ union
    { 
      __extension__ unsigned long long int __wseq;
      struct {
    unsigned int __low;
    unsigned int __high;
      } __wseq32;
    };
    __extension__ union
    { 
      __extension__ unsigned long long int __g1_start;
      struct {
    unsigned int __low;
    unsigned int __high;
      } __g1_start32;
    };
    unsigned int __g_refs[2];
    unsigned int __g_size[2];
    unsigned int __g1_orig_size;
    unsigned int __wrefs;
    unsigned int __g_signals[2];
  } __data;
  char __size[__SIZEOF_PTHREAD_COND_T];
  __extension__ long long int __align;
} pthread_cond_t;
```

Causes errors like this `Error: undefined identifier '_Anonymous_5', did you mean struct '_Anonymous_2'?`

This minimal version does the same kind of thing:
```
struct
{
    struct
    {
    };
} __thing;
```

**Comment by Temtaime** [comment]
```
struct
{
    struct
    {
    };
} __thing;
```
This code is not valid under some C implementations and i doubt there's any examples in real world applications.
Only unions can be anonymous.
Structs must be named.
So i consider added test https://github.com/atilaneves/dpp/commit/aa925da86117b281bd2f101c124bd35022bd8328#diff-637637bcb3c51188f8d259c7e878524de1b8fbd46d3caa4abe3addd34cc569d1R349 are wrong, implementing workarounds causes issues like #297
