### ISSUE TITLE
unknown type name 'uint32_t'

### ISSUE THREAD

**Issue by trikko** [atilaneves/dpp#307]
t.h:
```c
#include <stdint.h>
uint32_t test;
```

t.dpp:
```c
#include "t.h"

void main()
{
}
```

```> d++ t.dpp```

output:

```
Error: Error parsing '/tmp/libclangYrt380':
./t.h:3:1: error: unknown type name 'uint32_t'
Program exited with code 1
```

linux + libclang10 + dpp 0.4.9

Including inttypes.h makes things even worse.

**Comment by lulcat** [comment]
I'll add this worked fine for me, I compiled with clan 12.0.0 (and llvm), and latest dmd/ldc (2.99.1/1.29.0 or so).

**Comment by klknn** [comment]
I had the similar issue when I linked `clang-14` to `/usr/bin/clang` in ubuntu 22.04. When I changed it to clang-12, everything worked fine.
