### ISSUE TITLE
Guile

### ISSUE THREAD

**Issue by Immortalin** [atilaneves/dpp#36]
Guile is the language that I still could not link/embed on non C/C++ platforms. If you are up for the challenge, here's it is:
 https://www.gnu.org/software/guile/docs/guile-tut/tutorial.html

:D

**Comment by atilaneves** [comment]
I don't understand what it is you want here. Do you want to embed guile in D? What would that have to do with dpp?

**Comment by Immortalin** [comment]
Guile is particularly difficult to bind and embed for non-C systems. So I am curious if this can be done with dpp since my last attempt at doing it manually ended in failure.

**Comment by atilaneves** [comment]
I don't know - try it? File issues if you encounter any.
