### ISSUE TITLE
Cannot wrap Xeus Jupyter library due to missing support for libclang's UsingDeclaration cursor type

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#38]
echo_interpreter.dpp
#include "echo_interpreter.hpp"
#include "xeus/xguid.hpp"

> d++ echo_interpreter.dpp
Error: Cannot translate unknown cursor kind UsingDeclaration

~
~

**Comment by atilaneves** [comment]
C++ support isn't ready yet.
