### ISSUE TITLE
invalid - parameters are ignored

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#42]
d++ --print-cursors --include-path . --include-path support -a julia.dpp
There is no -a but it doesn't complain.  This is more of a problem if you guess -i will be --include-path and it isn't.

**Comment by atilaneves** [comment]
Invalid parameters have to be ignored since anything d++ doesn't understand gets passed to the underlying compiler. It would be impractical to add every option supported by dmd, ldc and gdc.
