### ISSUE TITLE
Higher order function transforms to incorrect code

### ISSUE THREAD

**Issue by baklava151** [atilaneves/dpp#43]
The following works fine

```
int binOp(int f(int x, int y), int a, int b);

//becomes

extern(C)
{
    int binOp(int function(int, int), int, int) @nogc nothrow;
}
```

However if you wrap the function's name that's being passed as an argument in parentheses, no "function" keyword is output

```
int binOp(int (f)(int x, int y), int a, int b);

//becomes

extern(C)
{
    int binOp(int (int, int), int, int) @nogc nothrow;
}
```

**Comment by atilaneves** [comment]
For future reference, putting parens around the function name makes the clang type for that parameter go from FunctionProto to Unexposed (with a canonical type that's a FunctionProto).
