### ISSUE TITLE
Fails on 'struct macro'

### ISSUE THREAD

**Issue by kuettler** [atilaneves/dpp#44]
A C header that contains a struct called `macro` cannot be included, since `macro` is a (reserved) keyword in D.

**Comment by kuettler** [comment]
This did not fix it for me. I am looking at the headers from [joe](https://joe-editor.sourceforge.io/), a text editor that supports keyboard macros. It features a C struct with the name `macro`. Somewhat legit. The name of this struct is used in a few places in all of joe's headers.

Obviously, the (feature request) generalizes to find a solution for all of D's reserved words that are not reserved in C and could be used for that reason.

**Comment by atilaneves** [comment]
I've clearly not had enough coffee. I somehow read that there was a macro called `macro` (which apparently was a bug anyway!), and not a struct.
