### ISSUE TITLE
Ignore 'register' keyword

### ISSUE THREAD

**Issue by baklava151** [atilaneves/dpp#47]
Pretty sure it doesn't even do anything on newer C compilers

**Comment by atilaneves** [comment]
Ignore it how?

**Comment by baklava151** [comment]
For example, I'm seeing 

```
void rdline(register FILE *f);
```

though I'm now realizing that this function prototype was directly in the original source file rather than coming from a header, so that's on me. I don't know if it's something you'd still want to watch for and discard in the .d file output.

**Comment by atilaneves** [comment]
I'm not sure what the issue is. Right now this:

```c
void foo(register int* thingie);
```

Becomes this:

```d
void foo(int*);
```

I don't think it's ever been any other way.

**Comment by baklava151** [comment]
Ah, it's not an issue then. Sorry for the confusion
