### ISSUE TITLE
typedef enum and typedef struct leaks through

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#5]
Okay - I'm dopey today.  I'm using include wrong.  I should run it on the pseudo-D source.

Maybe because of my typedef hack to turn the assert into a warning, but probably not.

```c
typedef enum zfs_error {
 EZFS_SUCCESS = 0,
 EZFS_NOMEM = 2000,
};
typedef struct zfs_perm_node {
 avl_node_t z_node;
 char z_pname[4096];
} zfs_perm_node_t;

typedef struct libzfs_handle libzfs_handle_t;
```

and a few more - strangely only at the last 1k lines of an 11k line file.

**Comment by Laeeth** [comment]
Another example (using my modified version that adds C_INCLUDE_PATH from environment to the search directories):
C_INCLUDE_PATH=/usr/include/libvirt bin/include /usr/include/libvirt/libvirt.h libvirt/libvirt.di
libvirt.di just doesn't have typedef conversions.  gist is here:

https://gist.github.com/Laeeth/0266ea4f6d359877bd90f1354953876f

start is:
```
import core.stdc.config;
import core.stdc.stdarg: va_list;
struct struct___locale_data { int dummy; }






typedef unsigned char __u_char;
typedef unsigned short int __u_short;
typedef unsigned int __u_int;
typedef unsigned long int __u_long;


typedef signed char __int8_t;
typedef unsigned char __uint8_t;
typedef signed short int __int16_t;
typedef unsigned short int __uint16_t;
typedef signed int __int32_t;
typedef unsigned int __uint32_t;

typedef signed long int __int64_t;
typedef unsigned long int __uint64_t;







typedef long int __quad_t;
typedef unsigned long int __u_quad_t;


```

**Comment by atilaneves** [comment]
I don't understand what the issue is.
