### ISSUE TITLE
[Request] Enable the wiki on this repo

### ISSUE THREAD

**Issue by bachmeil** [atilaneves/dpp#52]
Enabling the wiki on this repo would allow users to post information/examples about C libraries they have gotten to compile. It's rarely the case that you don't have to make modifications somewhere to work with a big C library. In any event, it would be good to have a list of libraries that are known to compile.

**Comment by atilaneves** [comment]
I created the first page. I don't know if I need to do anything else to enable you to edit it.

If you need to modify something to get a C library to work, I'd argue it's a dpp bug.

**Comment by bachmeil** [comment]
I'm not able to make changes to the wiki. Under the settings tab, there is an option "Restrict editing to collaborators only" that needs to be unchecked. I believe that will allow anyone to make edits.

**Comment by bachmeil** [comment]
> If you need to modify something to get a C library to work, I'd argue it's a dpp bug.

By that I meant that you can't always write reuse your C code when you're writing a D program, even if dpp is working correctly. It's therefore helpful to provide working examples as a lot of users of dpp will be new to D because they were attracted to D by dpp.

**Comment by atilaneves** [comment]
@bachmeil I've unchecked "restrict editing to collaborators only"

**Comment by bachmeil** [comment]
It works. I've posted some information. Hopefully others will post there as well.
