### ISSUE TITLE
Compilation fails due to `alias bool = int;`

### ISSUE THREAD

**Issue by bachmeil** [atilaneves/dpp#53]
I created a mex file to be loaded into Octave just fine using Octave 4.2.2. On an older machine, which has Octave 4.0.0, dpp generated

```
alias bool = int;
```

And that won't compile. I was translating one of the examples in the Octave manual to D. The full program is [here](https://github.com/bachmeil/dppexamples/blob/master/mex/mypow3.dpp).

**Comment by atilaneves** [comment]
I don't know what mex or Octave are, and there ano no links in the bug description. Thanks for the file, but I don't know how I'd reproduce the issue since there is no `mex.h` file for me to include and run dpp with.

I assume a header with `typedef int bool;` would suffice.

**Comment by bachmeil** [comment]
Here's a minimal example to reproduce the problem.

foo.h:

```
typedef int bool;
```

foo.dpp:

```
#include "foo.h"
void main() {}
```

Compile:

```
$ d++ foo.dpp
Error: Could not execute `dmd foo.d -offoo`:
foo.d(40): Error: no identifier for declarator `bool`
foo.d(40): Error: found `;` when expecting `.` following int
foo.d(41): Error: found `}` when expecting identifier following `int`.
foo.d(45): Error: alias cannot have initializer
foo.d(45): Error: semicolon expected to close `alias` declaration
foo.d(46): Error: matching `}` expected, not `End of File`
```

Offending code in foo.d:

```
extern(C)
{
    alias bool = int;
}
```
