### ISSUE TITLE
attributes ? @nogc @system ?

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#67]
should these be automatically applied?  or leave it to user to stick before the #includes ?

**Comment by atilaneves** [comment]
That's a good question. Currently `@nogc nothrow` are being automatically applied, which is what one wants 99% of the time but if a D function is passed as a callback, then the callback probably shouldn't be `@nogc nothrow`...

I'm not sure what to do about `@system`. It's the D default, so an argument could be made that should be the default translation as well.

I considered adding options for this, but your idea is better: just add `@safe { #include "header.h" }` and the same effect is achieved.

**Comment by Laeeth** [comment]
perhaps put in hints and tips on wiki
if we just capture the info in terse format maybe we can persuade somebody else to make it friendly and readable.

why wouldn't you want the callback to be nothrow?  it's not going to go well if it throws an exception.  on the other hand presently you might be quite sure it shouldn't throw but not be able to make it nothrow and if translating other code a nuisance to try catch for each one.

I guess @nogc might not be something you require.

at some point might want the ability to modify declarations declaratively.  blacklist and do it manually one way.  rust provides example of more refined approach.  but I think this is someday as value of C++ is much greater than this kind of tweak.  Ie I think blacklist is valuable and worry about rest later.

**Comment by atilaneves** [comment]
I added [a wiki page](https://github.com/atilaneves/dpp/wiki/D-attributes-for-the-translations)
