### ISSUE TITLE
aligned and packed?

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#68]
https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#Common-Type-Attributes

**Comment by atilaneves** [comment]
See:

https://github.com/atilaneves/dpp/blob/5d83c0e4239ff35509e08802a7822baed6826c99/tests/it/c/compile/projects.d#L476

https://github.com/atilaneves/dpp/blob/5d83c0e4239ff35509e08802a7822baed6826c99/tests/it/c/dstep/issues.d?utf8=%E2%9C%93#L169

https://github.com/atilaneves/dpp/blob/5d83c0e4239ff35509e08802a7822baed6826c99/tests/it/c/dstep/issues.d?utf8=%E2%9C%93#L177

https://github.com/atilaneves/dpp/blob/5d83c0e4239ff35509e08802a7822baed6826c99/tests/it/c/dstep/issues.d?utf8=%E2%9C%93#L193

https://github.com/atilaneves/dpp/blob/5d83c0e4239ff35509e08802a7822baed6826c99/tests/it/c/dstep/ut.d?utf8=%E2%9C%93#L405
