### ISSUE TITLE
Window support / bug

### ISSUE THREAD

**Issue by SrMordred** [atilaneves/dpp#80]
Some chance of windows support?
I build it with ldc2, but it gave me this:

d++ app.dpp
Error: Failed to spawn new process (system cannot find the file specified)

**Comment by atilaneves** [comment]
Windows support is planned but is not currently a priority. Feel free to help out with PRs.

The first thing that I know wouldn't work (and probably what caused your error message) is that dpp tries to call `cpp` to preprocess files, which isn't available on Windows. I don't know what else is needed since I haven't tried it on Windows yet.

**Comment by SrMordred** [comment]
I take a look briefly into some of the code.  
Part of the problem is that it call at some point "/dev/null" (which obviously doesn't exists on windows)
and back there at libclang , it break trying to parse (i believe) file paths with "(", ")" , like "Program Files(32)".

at the moment its more easy to me install a vm and ubuntu :P

**Comment by atilaneves** [comment]
`/dev/null` is easy, `version(Windows) "NUL"`. I'm not sure I understand the parsing error you just mentioned though.

**Comment by SrMordred** [comment]
nvm, was an error on the c file.
I got it working on windows :)
At least on an simple example.

The two details are the dev/null as mentioned and that on windows you link with .obj file and not .o

**Comment by atilaneves** [comment]
Awesome, please submit a PR.

**Comment by John-Colvin** [comment]
Any chance you could share what it was you changed, even if you don't have time for a pull request?

**Comment by SrMordred** [comment]
I believe that the only modification was not here but in libclang:
https://github.com/atilaneves/libclang/blob/master/source/clang/package.d#L84
`const res = execute(["clang", "-v", "-xc++", "/dev/null", "-fsyntax-only"], ["LANG": "C"]);`
removing the `/dev/null/`

I just didn't create the PR yet because I was really messing around just to see if it was possible, and i´m not sure now if it was the only change.

But if it was, then its a trivial PR :)

**Comment by veelo** [comment]
Should be resolved now.
