### ISSUE TITLE
Missing clang.lib on Windows when building

### ISSUE THREAD

**Issue by ZILtoid1991** [atilaneves/dpp#86]
Error message:
`Performing "release" build using C:\LDC\bin\ldc2.exe for x86_64.
libclang 0.0.11: target for configuration "library" is up to date.
dpp 0.0.2: building configuration "executable"...
LINK : fatal error LNK1181: cannot open input file 'clang.lib'
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\link.exe failed with status: 1181
C:\LDC\bin\ldc2.exe failed with exit code 1.`

I've upgraded my LLVM + CLang installation to the newest version, but that didn't fix the issue.

**Comment by atilaneves** [comment]
I'm guessing it's because the build doesn't know where to find the .lib file.

**Comment by ZILtoid1991** [comment]
Just checked out libclang's dub.json, and it seems it needs LLVM-3.9 (at least according to a few flags), which would conflict with the 7.0 I have.

Do you happen to have a compiled and working binary for Windows?

**Comment by atilaneves** [comment]
Not yet, see #80

**Comment by veelo** [comment]
Should be resolved now.
