### ISSUE TITLE
dmd fails (bad D output?)

### ISSUE THREAD

**Issue by chriscamacho** [atilaneves/dpp#89]
comment out just line 1608 and it will compile....
c source from https://bitbucket.org/odedevs/ode/downloads/
```
$ cat test.dpp
// /home/chris/development/ode-0.15.2/include


#include <ode/ode.h>
import std.stdio;

void main() {
    writeln("Hello!");

}
$ d++ --include-path /home/chris/development/ode-0.15.2/include test.dpp 
Error: Could not execute `dmd test.d -oftest`:
test.d(1608): Error: function declaration without return type. (Note that constructors are always named `this`)
test.d(1608): Error: found `*` when expecting `)`
test.d(1608): Error: semicolon expected following function declaration
test.d(1608): Error: declaration expected, not `,`

$ head -1609 test.d | tail -3
    alias dThreadReadyToServeCallback = void function(void*) @nogc nothrow;
    void dExternalThreadingServeMultiThreadedImplementation(dxThreadingImplementation*, void (void *)*, void*) @nogc nothrow;
    dxThreadingThreadPool* dThreadingAllocateThreadPool(uint, c_ulong, uint, void*) @nogc nothrow;
```

**Comment by atilaneves** [comment]
I can't reproduce this with the current master.  I went back to v0.0.5 and couldn't reproduce it with that version either.

**Comment by chriscamacho** [comment]
did you configure ode before trying this? , good chance this will have a bearing, I seem to remember the configuration generates a header file.
 There is also another issue which prevents use of the collision callback, I can get i working but it means manually editing the d source (which kinda defeats the point!)
I clone from master yesterday

**Comment by atilaneves** [comment]
I hadn't - I didn't really look at the ode files besides figuring out the headers were in `include`. Anyway, I ran `./configure` and tried again. No issue.
