### ISSUE TITLE
Problem with sizeof

### ISSUE THREAD

**Issue by trikko** [atilaneves/dpp#90]
This doesn't work:
```#define TEST(_ARR)          ((int)(sizeof(_ARR)/sizeof(*_ARR)))```

This works:
```#define TEST(_ARR)          ((int)(sizeof(_ARR)/sizeof((*_ARR))))```

The first is translated to  ..... /*_arr  and compiler parse it as comment.

**Comment by atilaneves** [comment]
Closed by !92
