### ISSUE TITLE
c++ template and unsigned short

### ISSUE THREAD

**Issue by trikko** [atilaneves/dpp#91]
I know this part is still a work in progess anyway:

```
template <typename T>
class Test
{
};

void test(Test<unsigned short> a);
```

This is translated to : 
```void test(Test!(unsigned short)) @nogc nothrow;```

but should be:
```void test(Test!(ushort)) @nogc nothrow;```

**Comment by atilaneves** [comment]
No, this part should work, the work-in-progress is with far more difficult corners of C++. Thanks for reporting the issue!
